ci: use `CHANGELOG-SNAPSHOTS.md` for changelog for pre-releases

diff --git a/.github/workflows/changelog-check.yml b/.github/workflows/changelog-check.yml
--- a/.github/workflows/changelog-check.yml
+++ b/.github/workflows/changelog-check.yml
@@ -41,10 +41,10 @@ jobs:
             echo "::error::CHANGELOG.md is not updated!"
             exit 1
           fi
-      - name: Changelog check for CHANGELOG-PRERELEASE.md
+      - name: Changelog check for CHANGELOG-SNAPSHOTS.md
         if: always() && !(fromJson(env.DOCUMENTATION) || fromJson(env.DOCUMENTATION) || fromJson(env.NO_CHANGELOG))
         run: |
-          if ! grep -e '^CHANGELOG-PRERELEASE.md' < files.txt > /dev/null; then
-            echo "::error::CHANGELOG-PRERELEASE.md is not updated!"
+          if ! grep -e '^CHANGELOG-SNAPSHOTS.md' < files.txt > /dev/null; then
+            echo "::error::CHANGELOG-SNAPSHOTS.md is not updated!"
             exit 1
           fi
